"""Deterministic confidence constants."""

RESUME_FIELD_CONFIDENCE = 0.95
CSV_FIELD_CONFIDENCE = 0.90
UNKNOWN_SOURCE_CONFIDENCE = 0.50

SOURCE_FIELD_CONFIDENCE = {
    "resume_pdf": RESUME_FIELD_CONFIDENCE,
    "recruiter_csv": CSV_FIELD_CONFIDENCE,
}

__all__ = [
    "CSV_FIELD_CONFIDENCE",
    "RESUME_FIELD_CONFIDENCE",
    "SOURCE_FIELD_CONFIDENCE",
    "UNKNOWN_SOURCE_CONFIDENCE",
]
